<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-EMLR0Q3" failures="1" tests="3" name="Test" time="8.089" errors="0" timestamp="2025-02-06T02:03:41 IST">
  <testcase classname="TestNG.Listeners.orangeHRM" name="testLogo" time="0.073"/>
  <testcase classname="TestNG.Listeners.orangeHRM" name="testUrl" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/web/index.php/auth/] but found [https://opensource-demo.orangehrmlive.com/web/index.php/auth/login]
at TestNG.Listeners.orangeHRM.testUrl(orangeHRM.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testUrl -->
  <testcase classname="TestNG.Listeners.orangeHRM" name="testTitle" time="0.0">
    <skipped/>
  </testcase> <!-- testTitle -->
</testsuite> <!-- Test -->
